### ISSUE TITLE
docs: Following the installation guide results in error on Hello World log. 

### ISSUE THREAD

**Issue by danielroek** [wolfenrain/fluttium#306]
**Description**

Not really sure what the improvement should be, as I have not yet solved the issue. But when following the guide on fluttium.dev, the first teste results in the following output:
```
  My first Fluttium flow.


 Fatal driver exception occurred: Invalid argument (name): An action with this name is not registered.: "log"
✓ Uninstalling test runner (1.4s)
```

I've tried to use the git-hosted log_action, but that did not help either. 

**Requirements**

- [ ] Update documentation so the setup works on the first try.

**Comment by wolfenrain** [comment]
Thanks for opening up an issue! Can you provide your Fluttium.yaml? I suspect either the path is wrong there or registering isn't working as intended (tho it should as with any bug haha)

**Comment by danielroek** [comment]
My fluttium.yaml is the default one that is generated by `fluttium init`:

```yaml
# The following defines the environment for your Fluttium project. It includes 
# the version of Fluttium that the project requires.
environment:
  fluttium: ">=0.1.0 <1.0.0"

# The driver can be configured with default values. Uncomment the following 
# lines to automatically run Fluttium using a different flavor and dart-defines.
  driver:
    target: lib/main_development.dart
    flavor: development
#   dart_defines:
#     - CUSTOM_DART_DEFINE=1

# Register actions which can be used within your Fluttium flows.
actions:
  # The following adds the log action to your project.
  log_action: 0.2.0
```
