### ISSUE TITLE
fix: Unable to find text in some TexdFields

### ISSUE THREAD

**Issue by danielroek** [wolfenrain/fluttium#308]
**Description**

Not really sure if I'm doing something wrong here, but I'm running into an issue where in one field I am able to use `expectVisible` and `pressOn` followed by `writeText`. But in a screen a bit later the `expectVisible` fails. 

**Steps To Reproduce**
My test yaml:
```yaml
description: Sign up to TrackBee using email and password.
---
- log: 'Running sign up flow'
- pressOn: 'Sign up'
- expectVisible: 'Email'
- pressOn: 'Email'
- writeText: 'test57@trackbee.io'
- pressOn: 'Password'
- writeText: 'test_password'
- pressOn: 'Repeat Password'
- writeText: 'test_password'
- pressOn: 'New account'
- pressOn: 'Accept Terms and Conditions'
- expectVisible: 'Next'
- expectVisible: 'Back'
- expectVisible: 'How do you want us to call you?'
```

**Expected Behavior**

Unable the field containing `How would you like us to call you?`
<img width="491" alt="image" src="https://github.com/wolfenrain/fluttium/assets/32639467/c687c977-84fa-49e7-bec5-db175c311a9e">
```dart
          FormBuilderTextField(
            key: const Key('name'),
            name: 'name',
            initialValue: state.name,
            onChanged: context.read<OnboardingCubit>().onChangeName,
            keyboardType: TextInputType.name,
            autofillHints: const <String>[AutofillHints.name],
            validator: FormBuilderValidators.required(
                errorText: AppLocalizations.of(context)!.requiredField),
            decoration: const InputDecoration(
              prefixIcon: Icon(Icons.account_circle_outlined),
              labelText: 'How would you like us to call you?',
              hintText: 'John',
            ),
          ),
```

It is able to find the following three fields:
<img width="402" alt="image" src="https://github.com/wolfenrain/fluttium/assets/32639467/3c0426ab-e47d-4f13-a9ec-3377536cec55">
```dart
    FormBuilderTextField(
      key: key,
      name: 'email',
      keyboardType: TextInputType.emailAddress,
      autofillHints: const <String>[AutofillHints.email],
      decoration: const InputDecoration(
        labelText: 'Email',
        hintText: 'name@company.com',
      ),
      validator: FormBuilderValidators.compose(<String? Function(String?)>[
        FormBuilderValidators.required(
            errorText: AppLocalizations.of(context)!.requiredField),
        FormBuilderValidators.email(
            errorText: AppLocalizations.of(context)!.invalidEmailError),
      ]),
    );
```

**Screenshots**

**Additional Context**

I've tried putting `wait`s between the steps, as these are inside an AnimatedSwitcher. But that did not help. I am able to find the next and back button on the page, but not the text in the fields.  

Hoping anyone has any advice. Happy to help if some extra information is needed
