### ISSUE TITLE
fix: for some reason, running on linux fails (git hub actions)

### ISSUE THREAD

**Issue by renancaraujo** [wolfenrain/fluttium#345]
**Description**

When trying to add fluttium to `very_good_flutter_plugin`, on linux, the workflow failed with the following log:

```log
⠋ Setting up the test runner...
✓ Setting up the test runner (96ms)
⠋ Setting up the launcher...
✓ Setting up the launcher (15ms)
⠋ Installing actions...
✓ Installing actions (2.2s)
⠋ Installing test runner...
✓ Installing test runner (4.4s)
⠋ Launching the test runner...
✓ Launching the test runner (27.6s)
00:00 +0: Press on "Get Platform Name"
00:01 +1: Check platform name: "Linux"
00:11 +1: Check platform name: "Linux"
⠋ Uninstalling test runner...
✓ Uninstalling test runner (1.4s)
Error: Process completed with exit code 75.
```

The workflow (job) code:
```yaml
  linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/my_plugin/my_plugin/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev

      - name: Install Fluttium
        run: flutter pub global activate fluttium_cli

      - name: E2E Tests
        run: xvfb-run fluttium test flows/test_platform_name.yaml -d linux
```

Link for the workflow file with the failing check:  https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/blob/36d4337a50fa61da6e3758a93f2db0d1668ea332/.github/workflows/my_plugin.yaml
