### ISSUE TITLE
fix: I cannot expect a string with a dollar sign in it

### ISSUE THREAD

**Issue by rekire** [wolfenrain/fluttium#407]
**Description**

I cannot expect that a string with a dollar sign is visible or not.

**Steps To Reproduce**

1. Open a shell
2. Install the CLI via `flutter pub global activate fluttium_cli` (on Windows 11 if that matters)
3. Go to your flutter project in my case [autologin/example](https://github.com/rekire/autologin_plugin/tree/main/autologin/example) (even not sure if that matters)
4. Run `fluttium new flow foo`
5. Use this three steps:
    ```yaml
    - pressOn: "Enter sample data"
    - expectVisible: "Some-Username"
    - expectNotVisible: "Example-P@§$w0rd!"
    ```
6. Execute the flow/test via `fluttium test .\foo.yaml`

**Expected Behavior**

A passed test. Actual I get a compile error.

**Screenshots**

```
Temp/fluttium_b62c6914/lib/fluttium_test_runner.dart:24:60: Error: Undefined name 'w0rd'.
    UserFlowStep.fromJson({"expectNotVisible":"Example-P@§$w0rd!"}),
                                                           ^^^^
Failed to compile application.
```

**Additional Context**

It is cool that you can click on icons when they have a tooltip.
